# Generated by Django 5.0.1 on 2025-11-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=100, verbose_name="שם פרטי / First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=100, verbose_name="שם משפחה / Last Name"
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="ת.ז / ID Number"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="טלפון / Phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="אימייל / Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="כתובת / Address"),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("BUYER", "רוכש רגיל / Regular Buyer"),
                            ("OWNER", "בעל דירה / Property Owner"),
                            ("INVESTOR", "משקיע / Investor"),
                            ("TENANT", "שוכר / Tenant"),
                        ],
                        default="BUYER",
                        max_length=20,
                        verbose_name="סוג לקוח / Customer Type",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="הערות / Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_number",
                    models.IntegerField(verbose_name="מספר תשלום / Payment #"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "מקדמה / Deposit"),
                            ("MILESTONE", "אבן דרך / Milestone"),
                            ("MONTHLY", "תשלום חודשי / Monthly"),
                            ("INTERMEDIATE", "תשלום ביניים / Intermediate Payment"),
                            ("FINAL", "תשלום סופי / Final Payment"),
                            ("BANK_TRANSFER", "העברה בנקאית / Bank Transfer"),
                            ("MORTGAGE", "משכנתא / Mortgage"),
                            ("OTHER", "אחר / Other"),
                        ],
                        max_length=20,
                        verbose_name="סוג תשלום / Payment Type",
                    ),
                ),
                (
                    "payment_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="תיאור / Description"
                    ),
                ),
                (
                    "scheduled_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="סכום מתוכנן / Scheduled Amount",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(verbose_name="תאריך מתוכנן / Scheduled Date"),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="סכום ששולם / Actual Amount Paid",
                    ),
                ),
                (
                    "actual_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="תאריך תשלום / Actual Payment Date",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "ממתין / Scheduled"),
                            ("PAID", "שולם / Paid"),
                            ("PARTIAL", "שולם חלקית / Partially Paid"),
                            ("OVERDUE", "באיחור / Overdue"),
                            ("CANCELLED", "בוטל / Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="סטטוס / Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "מזומן / Cash"),
                            ("CHECK", "שיק / Check"),
                            ("BANK_TRANSFER", "העברה בנקאית / Bank Transfer"),
                            ("CREDIT_CARD", "כרטיס אשראי / Credit Card"),
                            ("MORTGAGE", "משכנתא / Mortgage"),
                            ("OTHER", "אחר / Other"),
                        ],
                        max_length=20,
                        verbose_name="אמצעי תשלום / Payment Method",
                    ),
                ),
                (
                    "check_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="מספר שיק / Check Number",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="בנק / Bank Name"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="אסמכתא / Reference Number",
                    ),
                ),
                (
                    "days_delay",
                    models.IntegerField(
                        default=0, verbose_name="ימי איחור / Days Delay"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="הערות / Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Schedule",
                "verbose_name_plural": "Payment Schedules",
                "db_table": "customer_payment_schedule",
                "ordering": ["scheduled_date", "payment_number"],
            },
        ),
        migrations.CreateModel(
            name="SalesForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField(verbose_name="Forecast Date")),
                (
                    "month_year",
                    models.CharField(max_length=20, verbose_name="Month/Year"),
                ),
                (
                    "expected_sales_count",
                    models.IntegerField(default=0, verbose_name="Expected Sales Count"),
                ),
                (
                    "expected_revenue_nis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Expected Revenue (NIS)",
                    ),
                ),
                (
                    "cumulative_sales_count",
                    models.IntegerField(
                        default=0, verbose_name="Cumulative Sales Count"
                    ),
                ),
                (
                    "cumulative_revenue_nis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Cumulative Revenue (NIS)",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sales Forecast",
                "verbose_name_plural": "Sales Forecasts",
                "db_table": "sales_forecast",
                "ordering": ["forecast_date"],
            },
        ),
        migrations.CreateModel(
            name="SalesTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "רגיל / Regular Sale"),
                            ("COMPENSATION", "תמורה / Compensation"),
                            ("RENTAL", "השכרה / Rental"),
                        ],
                        default="REGULAR",
                        max_length=20,
                        verbose_name="סוג מכירה / Sale Type",
                    ),
                ),
                (
                    "agreement_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="תאריך הסכם / Agreement Date",
                    ),
                ),
                (
                    "contract_date",
                    models.DateField(verbose_name="תאריך חוזה / Contract Date"),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="תאריך מסירה / Delivery Date",
                    ),
                ),
                (
                    "sale_status",
                    models.CharField(
                        choices=[
                            ("AGREEMENT", "הסכם / Agreement"),
                            ("CONTRACT_SIGNED", "חוזה נחתם / Contract Signed"),
                            ("CANCELLED", "בוטל / Cancelled"),
                            ("COMPLETED", "הושלם / Completed"),
                        ],
                        default="AGREEMENT",
                        max_length=20,
                        verbose_name="סטטוס / Status",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="מחיר מקורי / Original Price",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="הנחה % / Discount Percent",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="הנחה סכום / Discount Amount",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="מחיר סופי / Final Price",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("CASH", "מזומן / Cash"),
                            ("MORTGAGE", "משכנתא / Mortgage"),
                            ("MIXED", "שילוב / Mixed"),
                            ("INSTALLMENTS", "תשלומים / Installments"),
                        ],
                        default="MIXED",
                        max_length=20,
                        verbose_name="אופן תשלום / Payment Terms",
                    ),
                ),
                (
                    "down_payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="מקדמה / Down Payment",
                    ),
                ),
                (
                    "mortgage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="משכנתא / Mortgage Amount",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="הערות / Notes")),
                (
                    "contract_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y/%m/",
                        verbose_name="קובץ חוזה / Contract File",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sale Transaction",
                "verbose_name_plural": "Sales Transactions",
                "db_table": "sales_transactions",
                "ordering": ["-contract_date"],
            },
        ),
        migrations.CreateModel(
            name="UnitMix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apartment_type",
                    models.CharField(max_length=100, verbose_name="Apartment Type"),
                ),
                ("units_count", models.IntegerField(verbose_name="Units Count")),
                (
                    "avg_net_area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Avg Net Area (sqm)",
                    ),
                ),
                (
                    "avg_gross_area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Avg Gross Area (sqm)",
                    ),
                ),
                (
                    "avg_balcony_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Avg Balcony Area (sqm)",
                    ),
                ),
                (
                    "avg_garden_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Avg Garden Area (sqm)",
                    ),
                ),
                ("is_penthouse", models.BooleanField(default=False)),
                ("is_duplex", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Unit Mix",
                "verbose_name_plural": "Unit Mix",
                "db_table": "unitmix_lines",
                "ordering": ["apartment_type"],
            },
        ),
        migrations.CreateModel(
            name="ApartmentInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building_number",
                    models.CharField(
                        max_length=10, verbose_name="בניין / Building Number"
                    ),
                ),
                (
                    "wing",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="אגף / Wing"
                    ),
                ),
                ("floor", models.IntegerField(verbose_name="קומה / Floor Number")),
                (
                    "unit_number",
                    models.CharField(max_length=20, verbose_name="מס' / Unit Number"),
                ),
                (
                    "plan_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="מס' עפ\"י תכנית בקשה / Plan Number",
                    ),
                ),
                (
                    "unit_unique_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Unit Unique ID"
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "דירה / Apartment"),
                            ("PENTHOUSE", "פנטהאוז / Penthouse"),
                            ("GARDEN", "גן / Garden Apartment"),
                            ("DUPLEX", "דופלקס / Duplex"),
                            ("MINI_PENTHOUSE", "מיני פנטהאוז / Mini Penthouse"),
                            ("OFFICE", "משרדים / Office"),
                            ("RETAIL", "מסחר / Retail"),
                            ("STORAGE", "מחסן / Storage"),
                            ("WAREHOUSE", "מחסן / Warehouse"),
                            ("INDUSTRIAL", "תעשיה / Industrial"),
                            ("LIGHT_INDUSTRIAL", "תעשיה קלה / Light Industrial"),
                            ("HALL", "אולם / Hall"),
                            ("LOGISTICS", "לוגיסטיקה / Logistics"),
                            ("PARKING_REGULAR", "חניה רגילה / Regular Parking"),
                            ("PARKING_TANDEM", "חניה טורקית / Tandem Parking"),
                            (
                                "PARKING_UNDERGROUND",
                                "חניה תת קרקעית / Underground Parking",
                            ),
                            ("PARKING_ELEVATED", "חניה עילית / Elevated Parking"),
                            ("OTHER", "אחר / Other"),
                        ],
                        default="APARTMENT",
                        max_length=30,
                        verbose_name="סוג נכס / Unit Type",
                    ),
                ),
                (
                    "unit_sub_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="סוג משני / Sub Type"
                    ),
                ),
                (
                    "room_count",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="חדרים / Room Count",
                    ),
                ),
                (
                    "unit_direction",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="כיוון / Unit Direction",
                    ),
                ),
                (
                    "net_area_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name='שטח נטו במ"ר / Net Area (sqm)',
                    ),
                ),
                (
                    "gross_area_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name='שטח ברוטו במ"ר / Gross Area (sqm)',
                    ),
                ),
                (
                    "unit_area_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name='שטח פלדלת במ"ר / Unit Area (sqm)',
                    ),
                ),
                (
                    "balcony_area_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name='מרפסת שמש במ"ר / Balcony Area (sqm)',
                    ),
                ),
                (
                    "terrace_area_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name='מרפסת במ"ר / Terrace Area (sqm)',
                    ),
                ),
                (
                    "roof_terrace_area_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name='מרפסת גג במ"ר / Roof Terrace Area (sqm)',
                    ),
                ),
                (
                    "yard_area_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name='חצר במ"ר / Yard Area (sqm)',
                    ),
                ),
                (
                    "gallery_area_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name='גלריה במ"ר / Gallery Area (sqm)',
                    ),
                ),
                (
                    "parking_spaces",
                    models.IntegerField(
                        default=0, verbose_name="חניות / Parking Spaces"
                    ),
                ),
                (
                    "storage_count",
                    models.IntegerField(
                        default=0, verbose_name="מחסנים / Storage Count"
                    ),
                ),
                (
                    "price_per_sqm_equivalent_with_vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name='שווי למ"ר אקוו\' כולל מע"מ / Price per sqm Equivalent (with VAT)',
                    ),
                ),
                (
                    "price_per_sqm_net_with_vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name='שווי למ"ר פלדלת כולל מע"מ / Price per sqm Net (with VAT)',
                    ),
                ),
                (
                    "price_per_sqm_no_vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name='שווי למ"ר לא כולל מע"מ / Price per sqm (No VAT)',
                    ),
                ),
                (
                    "list_price_with_vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name='שווי כולל מע"מ / List Price (with VAT)',
                    ),
                ),
                (
                    "list_price_no_vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name='שווי ללא מע"מ / List Price (No VAT)',
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="הנחה % / Discount Percent",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="הנחה סכום / Discount Amount",
                    ),
                ),
                (
                    "final_price_with_vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name='מחיר סופי כולל מע"מ / Final Price (with VAT)',
                    ),
                ),
                (
                    "final_price_no_vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name='מחיר סופי ללא מע"מ / Final Price (No VAT)',
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.17,
                        max_digits=5,
                        verbose_name='מע"מ / VAT Rate',
                    ),
                ),
                (
                    "unit_status",
                    models.CharField(
                        choices=[
                            ("FOR_SALE", "לשיווק / For Sale"),
                            ("SOLD", "נמכר / Sold"),
                            ("COMPENSATION", "תמורה / Compensation"),
                            ("FOR_RENT", "להשכרה / For Rent"),
                            ("RESERVED", "שמור / Reserved"),
                            ("IN_PROCESS", "בהליכים / In Process"),
                            ("UNAVAILABLE", "לא זמין / Unavailable"),
                        ],
                        default="FOR_SALE",
                        max_length=20,
                        verbose_name="סטטוס / Status",
                    ),
                ),
                (
                    "contract_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="תאריך חוזה / Contract Date"
                    ),
                ),
                (
                    "expected_delivery_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="תאריך מסירה / Expected Delivery Date",
                    ),
                ),
                (
                    "customer_first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="שם פרטי / First Name"
                    ),
                ),
                (
                    "customer_last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="שם משפחה / Last Name"
                    ),
                ),
                (
                    "sell_contract",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y/%m/",
                        verbose_name="חוזה / Sell Contract",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="projects.project",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apartments",
                        to="sales.customer",
                        verbose_name="לקוח / Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apartment",
                "verbose_name_plural": "Apartment Inventory",
                "db_table": "apartment_inventory",
                "ordering": ["building_number", "floor", "unit_number"],
            },
        ),
    ]
