# Generated by Django 5.0.1 on 2025-11-19 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesforecast",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_forecasts_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesforecast",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_forecasts",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="apartment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_transaction",
                to="sales.apartmentinventory",
                verbose_name="דירה / Apartment",
            ),
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="נוצר על ידי / Created By",
            ),
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="sales.customer",
                verbose_name="לקוח / Customer",
            ),
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_transactions",
                to="projects.project",
                verbose_name="פרויקט / Project",
            ),
        ),
        migrations.AddField(
            model_name="customerpaymentschedule",
            name="sales_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_schedule",
                to="sales.salestransaction",
                verbose_name="עסקת מכירה / Sales Transaction",
            ),
        ),
        migrations.CreateModel(
            name="SalesLine",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sales.salestransaction",),
        ),
        migrations.AddField(
            model_name="unitmix",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_mix",
                to="projects.project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apartmentinventory",
            unique_together={("project", "building_number", "floor", "unit_number")},
        ),
        migrations.AlterUniqueTogether(
            name="salesforecast",
            unique_together={("project", "month_year")},
        ),
    ]
