# Generated by Django 5.0.1 on 2025-11-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("TLV", "תל אביב-יפו / Tel Aviv"),
                            ("JRS", "ירושלים / Jerusalem"),
                            ("HFA", "חיפה / Haifa"),
                            ("BSV", "באר שבע / Beer Sheva"),
                            ("RSL", "ראשון לציון / Rishon LeZion"),
                            ("PTH", "פתח תקווה / Petah Tikva"),
                            ("NTN", "נתניה / Netanya"),
                            ("BNB", "בני ברק / Bnei Brak"),
                            ("HLN", "חולון / Holon"),
                            ("RMG", "רמת גן / Ramat Gan"),
                            ("ASD", "אשדוד / Ashdod"),
                            ("RHV", "רחובות / Rehovot"),
                            ("BSM", "בית שמש / Beit Shemesh"),
                            ("KFS", "כפר סבא / Kfar Saba"),
                            ("HRZ", "הרצליה / Herzliya"),
                            ("HDS", "הוד השרון / Hod HaSharon"),
                            ("RMS", "רמת השרון / Ramat HaSharon"),
                            ("ASK", "אשקלון / Ashkelon"),
                            ("RAN", "רעננה / Ra'anana"),
                            ("LOD", "לוד / Lod"),
                            ("RML", "רמלה / Ramla"),
                            ("NSZ", "נס ציונה / Ness Ziona"),
                            ("MDN", "מודיעין-מכבים-רעות / Modiin"),
                            ("YVN", "יבנה / Yavne"),
                            ("ELT", "אילת / Eilat"),
                            ("TVR", "טבריה / Tiberias"),
                            ("ZFT", "צפת / Safed"),
                            ("AKO", "עכו / Acre"),
                            ("NHR", "נהריה / Nahariya"),
                            ("AFL", "עפולה / Afula"),
                            ("KMZ", "קריית מוצקין / Kiryat Motzkin"),
                            ("KYM", "קריית ים / Kiryat Yam"),
                            ("KTA", "קריית אתא / Kiryat Ata"),
                            ("KBL", "קריית ביאליק / Kiryat Bialik"),
                            ("KRO", "קריית אונו / Kiryat Ono"),
                            ("KGT", "קריית גת / Kiryat Gat"),
                            ("KSM", "קריית שמונה / Kiryat Shmona"),
                            ("GVT", "גבעתיים / Givatayim"),
                            ("GVS", "גבעת שמואל / Givat Shmuel"),
                            ("BTY", "בת ים / Bat Yam"),
                            ("ORY", "אור יהודה / Or Yehuda"),
                            ("YHD", "יהוד-מונוסון / Yehud"),
                            ("ARD", "ערד / Arad"),
                            ("DMN", "דימונה / Dimona"),
                            ("NTV", "נתיבות / Netivot"),
                            ("OFQ", "אופקים / Ofakim"),
                            ("SDR", "שדרות / Sderot"),
                            ("BSN", "בית שאן / Beit Shean"),
                            ("MGD", "מגדל העמק / Migdal HaEmek"),
                            ("NZR", "נצרת / Nazareth"),
                            ("NGL", "נצרת עילית / Nof HaGalil"),
                            ("TKR", "טירת כרמל / Tirat Carmel"),
                            ("HDR", "חדרה / Hadera"),
                            ("KML", "כרמיאל / Karmiel"),
                            ("NSR", "נשר / Nesher"),
                            ("MLT", "מעלות-תרשיחא / Ma'alot-Tarshiha"),
                            ("MLA", "מעלה אדומים / Ma'ale Adumim"),
                            ("ARL", "אריאל / Ariel"),
                            ("ELD", "אלעד / Elad"),
                            ("RHT", "רהט / Rahat"),
                            ("ARB", "עראבה / Ar'ara"),
                            ("ORA", "אור עקיבא / Or Akiva"),
                            ("RSH", "ראש העין / Rosh HaAyin"),
                        ],
                        max_length=3,
                        verbose_name="עיר / City",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="מזהה פרויקט",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="שם הפרויקט"),
                ),
                (
                    "project_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="תיאור הפרויקט"
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("PRE_CONSTRUCTION", "Pre-Construction"),
                            ("CONSTRUCTION", "Construction"),
                        ],
                        default="PRE_CONSTRUCTION",
                        max_length=20,
                        verbose_name="שלב פרויקט",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "פרויקט",
                "verbose_name_plural": "פרויקטים",
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="ProjectDataInputs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_details",
                    models.JSONField(blank=True, null=True, verbose_name="פרטי נכס"),
                ),
                (
                    "dates",
                    models.JSONField(blank=True, null=True, verbose_name="תאריכים"),
                ),
                (
                    "developer",
                    models.JSONField(blank=True, null=True, verbose_name="פרטי יזם"),
                ),
                (
                    "financing",
                    models.JSONField(blank=True, null=True, verbose_name="פרטי מימון"),
                ),
                (
                    "profitability",
                    models.JSONField(blank=True, null=True, verbose_name="רווחיות"),
                ),
                (
                    "land_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="ערך קרקע / דוח אפס"
                    ),
                ),
                (
                    "fixed_rates",
                    models.JSONField(
                        blank=True, null=True, verbose_name="שיעורים קבועים"
                    ),
                ),
                (
                    "insurance",
                    models.JSONField(blank=True, null=True, verbose_name="ביטוח"),
                ),
                (
                    "construction_classification",
                    models.JSONField(blank=True, null=True, verbose_name="סיווג בנייה"),
                ),
                (
                    "guarantees",
                    models.JSONField(blank=True, null=True, verbose_name="ערבויות"),
                ),
                (
                    "sensitivity_analysis",
                    models.JSONField(
                        blank=True, null=True, verbose_name="ניתוח רגישות"
                    ),
                ),
                (
                    "monthly_cashflow",
                    models.JSONField(
                        blank=True, null=True, verbose_name="תזרים מזומנים חודשי"
                    ),
                ),
                (
                    "revenue_forecast",
                    models.JSONField(
                        blank=True, null=True, verbose_name="תחזית הכנסות"
                    ),
                ),
                (
                    "cost_forecast",
                    models.JSONField(
                        blank=True, null=True, verbose_name="תחזית עלויות"
                    ),
                ),
                (
                    "project_description_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="תיאור פרויקט - טקסט"
                    ),
                ),
                (
                    "project_description_table",
                    models.JSONField(
                        blank=True, null=True, verbose_name="תיאור פרויקט - טבלה"
                    ),
                ),
                (
                    "timeline_dates",
                    models.JSONField(blank=True, null=True, verbose_name="לוחות זמנים"),
                ),
                (
                    "sales_timeline",
                    models.JSONField(blank=True, null=True, verbose_name="לוח מכירות"),
                ),
                (
                    "break_even",
                    models.JSONField(blank=True, null=True, verbose_name="נקודת איזון"),
                ),
                (
                    "index_values",
                    models.JSONField(blank=True, null=True, verbose_name="מדדים"),
                ),
                (
                    "cashflow",
                    models.JSONField(
                        blank=True, null=True, verbose_name="תזרים מזומנים"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_inputs",
                        to="projects.project",
                        verbose_name="פרויקט",
                    ),
                ),
            ],
            options={
                "verbose_name": "נתוני קלט פרויקט",
                "verbose_name_plural": "נתוני קלט פרויקטים",
                "db_table": "project_data_inputs",
            },
        ),
    ]
