# Generated by Django 5.0.1 on 2025-11-24 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        help_text="תאריך ביצוע ההוצאה", verbose_name="תאריך הוצאה"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="קטגוריית עלות (מתאימה לתחזית העלויות)",
                        max_length=200,
                        verbose_name="קטגוריה",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        help_text="תיאור הסעיף", max_length=300, verbose_name="סעיף"
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ספק/נותן שירות"
                    ),
                ),
                (
                    "amount_no_vat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text='הסכום ללא מע"מ',
                        max_digits=15,
                        verbose_name='סכום ללא מע"מ',
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=17.0,
                        help_text='שיעור המע"מ באחוזים',
                        max_digits=5,
                        verbose_name='שיעור מע"מ (%)',
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text='סכום המע"מ',
                        max_digits=15,
                        verbose_name='סכום מע"מ',
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text='סכום כולל מע"מ',
                        max_digits=15,
                        verbose_name="סכום כולל",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "מזומן / Cash"),
                            ("CHECK", "המחאה / Check"),
                            ("BANK_TRANSFER", "העברה בנקאית / Bank Transfer"),
                            ("CREDIT_CARD", "כרטיס אשראי / Credit Card"),
                            ("OTHER", "אחר / Other"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=20,
                        verbose_name="אמצעי תשלום",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "ממתין לתשלום / Pending"),
                            ("PAID", "שולם / Paid"),
                            ("OVERDUE", "באיחור / Overdue"),
                            ("CANCELLED", "בוטל / Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="סטטוס תשלום",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="תאריך תשלום בפועל"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="תאריך פירעון"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="מספר חשבונית"
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expenses/receipts/%Y/%m/",
                        verbose_name="קובץ חשבונית/קבלה",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="הערות")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="תאריך יצירה"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="תאריך עדכון"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נוצר על ידי",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="projects.project",
                        verbose_name="פרויקט",
                    ),
                ),
            ],
            options={
                "verbose_name": "הוצאת פרויקט",
                "verbose_name_plural": "הוצאות פרויקט",
                "db_table": "project_expenses",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="expenses/attachments/%Y/%m/", verbose_name="קובץ"
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="שם קובץ")),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="סוג קובץ"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, verbose_name="תיאור"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="תאריך העלאה"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="הועלה על ידי",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="projects.projectexpense",
                        verbose_name="הוצאה",
                    ),
                ),
            ],
            options={
                "verbose_name": "קובץ מצורף להוצאה",
                "verbose_name_plural": "קבצים מצורפים להוצאות",
                "db_table": "expense_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("LEUMI", "בנק לאומי / Bank Leumi"),
                            ("HAPOALIM", "בנק הפועלים / Bank Hapoalim"),
                            ("DISCOUNT", "בנק דיסקונט / Discount Bank"),
                            ("MIZRAHI", "בנק מזרחי טפחות / Mizrahi-Tefahot Bank"),
                            ("INTERNATIONAL", "הבינלאומי / First International Bank"),
                            ("JERUSALEM", "בנק ירושלים / Bank of Jerusalem"),
                            ("MERCANTILE", "בנק מרכנתיל / Mercantile Discount Bank"),
                            ("UNION", "בנק יהב / Bank Yahav"),
                            ("OTSAR_HAHAYAL", "בנק אוצר החיל / Bank Otsar Ha-Hayal"),
                            ("MASSAD", "בנק מסד / Bank Massad"),
                            (
                                "POALEI_AGUDAT",
                                "בנק פועלי אגודת ישראל / Bank Poalei Agudat Israel",
                            ),
                            ("OTHER", "אחר / Other"),
                        ],
                        max_length=50,
                        verbose_name="בנק",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="מספר חשבון"
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="תאריך תנועה")),
                (
                    "value_date",
                    models.DateField(blank=True, null=True, verbose_name="יום ערך"),
                ),
                ("description", models.TextField(verbose_name="תיאור התנועה")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="אסמכתא"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEBIT", "חובה / Debit"),
                            ("CREDIT", "זכות / Credit"),
                        ],
                        max_length=10,
                        verbose_name="סוג תנועה",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="סכום"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="יתרה",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "ממתין / Pending"),
                            ("APPROVED", "מאושר / Approved"),
                            ("REJECTED", "נדחה / Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="סטטוס",
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות אישור"),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="אושר על ידי",
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך אישור"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="קטגוריה"
                    ),
                ),
                (
                    "is_construction_related",
                    models.BooleanField(default=False, verbose_name="קשור לבנייה"),
                ),
                (
                    "meets_plan",
                    models.BooleanField(default=False, verbose_name="עומד בתוכנית"),
                ),
                (
                    "meets_construction_stage",
                    models.BooleanField(default=False, verbose_name="עומד בשלב בנייה"),
                ),
                (
                    "uploaded_file",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="קובץ מקור"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transactions",
                        to="projects.project",
                        verbose_name="פרויקט",
                    ),
                ),
            ],
            options={
                "verbose_name": "תנועת בנק",
                "verbose_name_plural": "תנועות בנק",
                "db_table": "bank_transactions",
                "ordering": ["-transaction_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["project", "transaction_date"],
                        name="bank_transa_project_a0881c_idx",
                    ),
                    models.Index(
                        fields=["project", "status"],
                        name="bank_transa_project_5c043a_idx",
                    ),
                    models.Index(
                        fields=["bank", "account_number"],
                        name="bank_transa_bank_b99b7a_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="projectexpense",
            index=models.Index(
                fields=["project", "expense_date"],
                name="project_exp_project_a38cfe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectexpense",
            index=models.Index(
                fields=["project", "category"], name="project_exp_project_d90ff5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectexpense",
            index=models.Index(
                fields=["payment_status"], name="project_exp_payment_ad2c22_idx"
            ),
        ),
    ]
