# Generated by Django 5.0.1 on 2025-11-24 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectexpense_expenseattachment_banktransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_contract_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="סכום חוזה כולל"
                    ),
                ),
                (
                    "available_floors",
                    models.JSONField(default=list, verbose_name="קומות זמינות"),
                ),
                ("tasks", models.JSONField(default=list, verbose_name="משימות בנייה")),
                (
                    "overall_completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="אחוז השלמה כולל",
                    ),
                ),
                (
                    "total_spent_to_date",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="סכום שהוצא עד היום",
                    ),
                ),
                (
                    "original_file_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="שם קובץ מקורי",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך העלאה"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="construction_progress",
                        to="projects.project",
                        verbose_name="פרויקט",
                    ),
                ),
            ],
            options={
                "verbose_name": "התקדמות בנייה",
                "verbose_name_plural": "התקדמות בנייה",
                "db_table": "construction_progress",
            },
        ),
        migrations.CreateModel(
            name="ConstructionProgressSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(verbose_name="תאריך צילום")),
                ("month", models.IntegerField(verbose_name="חודש")),
                ("year", models.IntegerField(verbose_name="שנה")),
                ("tasks_snapshot", models.JSONField(verbose_name="צילום משימות")),
                (
                    "overall_completion_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="אחוז השלמה כולל"
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="סכום שהוצא"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="נוצר על ידי",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_snapshots",
                        to="projects.project",
                        verbose_name="פרויקט",
                    ),
                ),
            ],
            options={
                "verbose_name": "צילום התקדמות",
                "verbose_name_plural": "צילומי התקדמות",
                "db_table": "construction_progress_snapshots",
                "ordering": ["-snapshot_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["project", "snapshot_date"],
                        name="constructio_project_d3a27d_idx",
                    ),
                    models.Index(
                        fields=["project", "year", "month"],
                        name="constructio_project_5f820f_idx",
                    ),
                ],
                "unique_together": {("project", "year", "month")},
            },
        ),
    ]
