# Generated by Django 5.0.1 on 2025-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_constructionprogress_constructionprogresssnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransaction",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PURCHASE_RECEIPTS", "קבלות רכישה / Purchase Receipts"),
                    ("LOANS", "הלוואות / Loans"),
                    ("OWNER_EQUITY", "הון עצמי / Owner Equity"),
                    ("BANK_FEES", "עמלות בנק / Bank Fees"),
                    ("TAX_PAYMENTS", "תשלומי מס / Tax Payments"),
                    ("CONTRACTOR_PAYMENTS", "תשלומים לקבלנים / Contractor Payments"),
                    ("SUPPLIER_PAYMENTS", "תשלומים לספקים / Supplier Payments"),
                    ("PROFESSIONAL_FEES", "שכר טרחה מקצועית / Professional Fees"),
                    ("INSURANCE", "ביטוח / Insurance"),
                    ("PERMITS_FEES", "אגרות והיתרים / Permits & Fees"),
                    ("MARKETING", "שיווק / Marketing"),
                    ("SALES_INCOME", "הכנסות ממכירות / Sales Income"),
                    ("REFUNDS", "החזרים / Refunds"),
                    ("OTHER_INCOME", "הכנסות אחרות / Other Income"),
                    ("OTHER_EXPENSE", "הוצאות אחרות / Other Expenses"),
                ],
                max_length=50,
                null=True,
                verbose_name="קטגוריה",
            ),
        ),
    ]
