# Generated by Django 5.0.1 on 2025-12-01 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_banktransaction_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquityDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deposit_date", models.DateField(verbose_name="תאריך הפקדה")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="סכום"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "הזנה ידנית / Manual Entry"),
                            ("TRANSFER", "העברה בנקאית / Bank Transfer"),
                            ("CHECK", "צ'ק / Check"),
                            ("CASH", "מזומן / Cash"),
                            ("BANK_TRANSACTION", "תנועת בנק / Bank Transaction"),
                            ("OTHER", "אחר / Other"),
                        ],
                        default="MANUAL",
                        max_length=20,
                        verbose_name="מקור",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="תיאור"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="אסמכתא"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="נוצר על ידי",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equity_deposits",
                        to="projects.banktransaction",
                        verbose_name="תנועת בנק מקושרת",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equity_deposits",
                        to="projects.project",
                        verbose_name="פרויקט",
                    ),
                ),
            ],
            options={
                "verbose_name": "הפקדת הון עצמי",
                "verbose_name_plural": "הפקדות הון עצמי",
                "db_table": "equity_deposits",
                "ordering": ["-deposit_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["project", "deposit_date"],
                        name="equity_depo_project_39e2ca_idx",
                    )
                ],
            },
        ),
    ]
