# Generated by Django 5.0.1 on 2025-12-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_equitydeposit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="שם המסמך")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="תיאור"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "חוזה / Contract"),
                            ("PERMIT", "היתר / Permit"),
                            ("PLAN", "תכנית / Plan"),
                            ("REPORT", "דוח / Report"),
                            ("INVOICE", "חשבונית / Invoice"),
                            ("BANK", "בנק / Bank"),
                            ("LEGAL", "משפטי / Legal"),
                            ("INSURANCE", "ביטוח / Insurance"),
                            ("ARCHITECT", "אדריכלות / Architecture"),
                            ("ENGINEERING", "הנדסה / Engineering"),
                            ("MARKETING", "שיווק / Marketing"),
                            ("PHOTOS", "תמונות / Photos"),
                            ("OTHER", "אחר / Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="קטגוריה",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="project_documents/%Y/%m/", verbose_name="קובץ"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="שם קובץ מקורי"),
                ),
                ("file_size", models.IntegerField(verbose_name="גודל קובץ (בבתים)")),
                (
                    "file_type",
                    models.CharField(max_length=100, verbose_name="סוג קובץ"),
                ),
                (
                    "document_date",
                    models.DateField(blank=True, null=True, verbose_name="תאריך מסמך"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="תגיות"),
                ),
                (
                    "uploaded_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="הועלה על ידי",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                        verbose_name="פרויקט",
                    ),
                ),
            ],
            options={
                "verbose_name": "מסמך פרויקט",
                "verbose_name_plural": "מסמכי פרויקט",
                "db_table": "project_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "category"],
                        name="project_doc_project_c6b6fb_idx",
                    ),
                    models.Index(
                        fields=["project", "created_at"],
                        name="project_doc_project_edc023_idx",
                    ),
                ],
            },
        ),
    ]
