# Generated by Django 5.0.1 on 2025-12-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_add_project_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="תאריך מחיקה / Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="פעיל / Active"),
        ),
    ]
