# Generated by Django 5.0.1 on 2025-12-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_add_soft_delete_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="מספר שינוי",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "הכנסה / Income"),
                            ("COST", "עלות / Cost"),
                            ("DURATION", "משך זמן / Duration"),
                            ("BUDGET", "תקציב / Budget"),
                            ("FINANCING", "מימון / Financing"),
                            ("SCOPE", "היקף / Scope"),
                            ("OTHER", "אחר / Other"),
                        ],
                        max_length=20,
                        verbose_name="סוג שינוי",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="כותרת")),
                ("description", models.TextField(verbose_name="תיאור השינוי")),
                (
                    "original_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="ערך מקורי",
                    ),
                ),
                (
                    "requested_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="ערך מבוקש",
                    ),
                ),
                (
                    "approved_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="ערך מאושר",
                    ),
                ),
                (
                    "impact_on_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="השפעה על התקציב",
                    ),
                ),
                (
                    "original_duration_months",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="משך זמן מקורי (חודשים)"
                    ),
                ),
                (
                    "requested_duration_months",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="משך זמן מבוקש (חודשים)"
                    ),
                ),
                (
                    "approved_duration_months",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="משך זמן מאושר (חודשים)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "טיוטה / Draft"),
                            ("PENDING", "ממתין לאישור / Pending Approval"),
                            ("APPROVED", "מאושר / Approved"),
                            ("REJECTED", "נדחה / Rejected"),
                            ("IMPLEMENTED", "יושם / Implemented"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="סטטוס",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "נמוך / Low"),
                            ("MEDIUM", "בינוני / Medium"),
                            ("HIGH", "גבוה / High"),
                            ("CRITICAL", "קריטי / Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="עדיפות",
                    ),
                ),
                (
                    "bank_approval_required",
                    models.BooleanField(default=False, verbose_name="נדרש אישור בנק"),
                ),
                (
                    "bank_approved",
                    models.BooleanField(default=False, verbose_name="אושר על ידי הבנק"),
                ),
                (
                    "bank_approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="תאריך אישור הבנק"
                    ),
                ),
                (
                    "bank_approval_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="הערות אישור הבנק"
                    ),
                ),
                (
                    "requested_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="מבקש השינוי",
                    ),
                ),
                (
                    "requested_date",
                    models.DateField(auto_now_add=True, verbose_name="תאריך בקשה"),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="מאשר השינוי",
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(blank=True, null=True, verbose_name="תאריך אישור"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, null=True, verbose_name="סיבת דחייה"),
                ),
                (
                    "implemented_date",
                    models.DateField(blank=True, null=True, verbose_name="תאריך יישום"),
                ),
                (
                    "implementation_notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות יישום"),
                ),
                (
                    "related_documents",
                    models.JSONField(
                        blank=True, default=list, verbose_name="מסמכים קשורים"
                    ),
                ),
                (
                    "affected_budget_items",
                    models.JSONField(
                        blank=True, default=list, verbose_name="סעיפי תקציב מושפעים"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="projects.project",
                        verbose_name="פרויקט",
                    ),
                ),
            ],
            options={
                "verbose_name": "שינוי פרויקט",
                "verbose_name_plural": "שינויי פרויקט",
                "db_table": "project_changes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="project_cha_project_b7d4ce_idx",
                    ),
                    models.Index(
                        fields=["project", "change_type"],
                        name="project_cha_project_433a79_idx",
                    ),
                    models.Index(
                        fields=["project", "created_at"],
                        name="project_cha_project_301050_idx",
                    ),
                ],
            },
        ),
    ]
