# Generated by Django 5.0.1 on 2025-12-02 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Nectra",
                        max_length=100,
                        verbose_name="שם חברה / Company Name",
                    ),
                ),
                (
                    "dark_mode",
                    models.BooleanField(
                        default=False, verbose_name="מצב כהה / Dark Mode"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("he", "עברית"), ("en", "English")],
                        default="he",
                        max_length=5,
                        verbose_name="שפה / Language",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="התראות במייל / Email Notifications"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="משתמש / User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
                "db_table": "user_settings",
            },
        ),
    ]
