# Generated by Django 5.0.1 on 2025-12-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_add_soft_delete_fields"),
        ("users", "0003_add_user_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="שם חברה / Company Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="אימייל / Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="טלפון / Phone"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="כתובת / Address"),
                ),
                (
                    "business_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ח.פ. / Business Number"
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("TRIAL", "ניסיון / Trial"),
                            ("STARTER", "סטארטר / Starter"),
                            ("PROFESSIONAL", "מקצועי / Professional"),
                            ("ENTERPRISE", "ארגוני / Enterprise"),
                        ],
                        default="TRIAL",
                        max_length=20,
                        verbose_name="תכנית / Subscription Plan",
                    ),
                ),
                (
                    "subscription_expires",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="תאריך תפוגה / Subscription Expires",
                    ),
                ),
                (
                    "max_projects",
                    models.IntegerField(
                        default=2, verbose_name="מקסימום פרויקטים / Max Projects"
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=5, verbose_name="מקסימום משתמשים / Max Users"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="פעיל / Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "חברה / Company",
                "verbose_name_plural": "חברות / Companies",
                "db_table": "companies",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "משתמש / User",
                "verbose_name_plural": "משתמשים / Users",
            },
        ),
        migrations.AlterModelOptions(
            name="usersettings",
            options={
                "verbose_name": "הגדרות משתמש / User Settings",
                "verbose_name_plural": "הגדרות משתמשים / User Settings",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_users",
                to="projects.project",
                verbose_name="פרויקטים משויכים / Assigned Projects",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="טלפון / Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "מנהל מערכת / Super Admin"),
                    ("COMPANY_ADMIN", "מנהל חברה / Company Admin"),
                    ("PROJECT_MANAGER", "מנהל פרויקט / Project Manager"),
                    ("ACCOUNTANT", "חשב / Accountant"),
                    ("FIELD_SUPERVISOR", "מפקח שטח / Field Supervisor"),
                    ("CONTRACTOR", "קבלן משנה / Contractor"),
                    ("VIEWER", "צופה / Viewer"),
                    ("BANK_LIAISON", "נציג בנק / Bank Liaison"),
                ],
                default="VIEWER",
                max_length=20,
                verbose_name="תפקיד / Role",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.company",
                verbose_name="חברה / Company",
            ),
        ),
    ]
