# Generated by Django 5.0.1 on 2025-12-01 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0004_alter_banktransaction_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=200, verbose_name="שם חברה / Company Name"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="ח.פ / עוסק מורשה / Tax ID",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="איש קשר / Contact Name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="טלפון / Phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="אימייל / Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="כתובת / Address"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="פעיל / Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="contractors",
                        to="projects.project",
                        verbose_name="פרויקטים / Projects",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="משתמש / User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contractor",
                "verbose_name_plural": "Contractors",
                "db_table": "contractors",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="מספר חשבונית / Invoice Number",
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="תאריך חשבונית / Invoice Date",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="תאריך לתשלום / Due Date"
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="שם ספק / Vendor Name"
                    ),
                ),
                (
                    "vendor_tax_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="ח.פ ספק / Vendor Tax ID",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name='סכום לפני מע"מ / Net Amount',
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name='מע"מ / VAT Amount',
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="סכום כולל / Total Amount",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECT_BUILDING", "בנייה ישירה / Direct Building"),
                            ("CONSULTING", "ייעוץ / Consulting"),
                            ("PLANNING", "תכנון / Planning & Architecture"),
                            ("SUPERVISION", "פיקוח / Supervision"),
                            ("MATERIALS", "חומרים / Materials"),
                            ("EQUIPMENT", "ציוד / Equipment"),
                            ("LABOR", "עבודה / Labor"),
                            ("SUBCONTRACTOR", "קבלן משנה / Subcontractor"),
                            ("TAXES", "מיסים / Taxes"),
                            ("FEES", "אגרות / Fees & Permits"),
                            ("INSURANCE", "ביטוח / Insurance"),
                            ("LEGAL", "משפטי / Legal"),
                            ("MARKETING", "שיווק / Marketing"),
                            ("FINANCE", "מימון / Finance Costs"),
                            ("GENERAL", "הוצאות כלליות / General Expenses"),
                            ("OTHER", "אחר / Other"),
                        ],
                        max_length=30,
                        verbose_name="קטגוריה / Category",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_OCR", "ממתין לעיבוד / Pending OCR"),
                            ("OCR_FAILED", "עיבוד נכשל / OCR Failed"),
                            ("PENDING_REVIEW", "ממתין לאישור / Pending Review"),
                            ("APPROVED", "מאושר / Approved"),
                            ("REJECTED", "נדחה / Rejected"),
                            ("PAID", "שולם / Paid"),
                        ],
                        default="PENDING_OCR",
                        max_length=20,
                        verbose_name="סטטוס / Status",
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        upload_to="invoices/%Y/%m/",
                        verbose_name="קובץ מקורי / Original File",
                    ),
                ),
                (
                    "ocr_raw_data",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="נתוני OCR גולמיים / Raw OCR Data",
                    ),
                ),
                (
                    "ocr_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="רמת ביטחון OCR / OCR Confidence",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="תיאור / Description"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="הערות / Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_invoices",
                        to="projects.banktransaction",
                        verbose_name="תנועת בנק / Bank Transaction",
                    ),
                ),
                (
                    "construction_progress",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="projects.constructionprogress",
                        verbose_name="סעיף התקדמות בנייה / Construction Progress Item",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="contractors.contractor",
                        verbose_name="קבלן / Contractor",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_invoices",
                        to="projects.project",
                        verbose_name="פרויקט / Project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="הועלה על ידי / Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "contractor_invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("APPROVE", "אישור / Approve"),
                            ("REJECT", "דחייה / Reject"),
                            ("REQUEST_CHANGES", "בקשת שינויים / Request Changes"),
                        ],
                        max_length=20,
                        verbose_name="פעולה / Action",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, verbose_name="הערות / Comments"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="מאשר / Approved By",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="contractors.invoice",
                        verbose_name="חשבונית / Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Approval",
                "verbose_name_plural": "Invoice Approvals",
                "db_table": "invoice_approvals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActualCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="שנה / Year")),
                ("month", models.IntegerField(verbose_name="חודש / Month")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DIRECT_BUILDING", "בנייה ישירה / Direct Building"),
                            ("CONSULTING", "ייעוץ / Consulting"),
                            ("PLANNING", "תכנון / Planning & Architecture"),
                            ("SUPERVISION", "פיקוח / Supervision"),
                            ("MATERIALS", "חומרים / Materials"),
                            ("EQUIPMENT", "ציוד / Equipment"),
                            ("LABOR", "עבודה / Labor"),
                            ("SUBCONTRACTOR", "קבלן משנה / Subcontractor"),
                            ("TAXES", "מיסים / Taxes"),
                            ("FEES", "אגרות / Fees & Permits"),
                            ("INSURANCE", "ביטוח / Insurance"),
                            ("LEGAL", "משפטי / Legal"),
                            ("MARKETING", "שיווק / Marketing"),
                            ("FINANCE", "מימון / Finance Costs"),
                            ("GENERAL", "הוצאות כלליות / General Expenses"),
                            ("OTHER", "אחר / Other"),
                        ],
                        max_length=30,
                        verbose_name="קטגוריה / Category",
                    ),
                ),
                (
                    "total_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='סה"כ לפני מע"מ / Total Net',
                    ),
                ),
                (
                    "total_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='סה"כ מע"מ / Total VAT',
                    ),
                ),
                (
                    "total_gross",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name='סה"כ כולל / Total Gross',
                    ),
                ),
                (
                    "invoice_count",
                    models.IntegerField(
                        default=0, verbose_name="מספר חשבוניות / Invoice Count"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_costs",
                        to="projects.project",
                        verbose_name="פרויקט / Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actual Cost",
                "verbose_name_plural": "Actual Costs",
                "db_table": "actual_costs",
                "ordering": ["-year", "-month", "category"],
                "unique_together": {("project", "year", "month", "category")},
            },
        ),
    ]
