# Generated by Django 5.0.1 on 2025-12-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="contractors.contractor",
                verbose_name="קבלן / Contractor",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="original_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="invoices/%Y/%m/",
                verbose_name="קובץ מקורי / Original File",
            ),
        ),
    ]
