# Generated by Django 5.0.1 on 2025-11-19 14:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquityApprovalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created by Appraiser"),
                            ("SUBMITTED", "Submitted for Validation"),
                            ("VALIDATED", "Validated by Team Manager"),
                            ("REJECTED", "Rejected by Team Manager"),
                            ("MODIFIED", "Modified by Appraiser"),
                            ("AMOUNT_CHANGED", "Validated Amount Changed"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("BANK_APPROVED", "Approved by Bank"),
                        ],
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Previous Status"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="New Status"
                    ),
                ),
                (
                    "previous_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Previous Amount",
                    ),
                ),
                (
                    "new_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="New Amount",
                    ),
                ),
                ("action_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Equity Approval History",
                "verbose_name_plural": "Equity Approval History",
                "ordering": ["-action_date"],
            },
        ),
        migrations.CreateModel(
            name="EquityRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=200, verbose_name="Bank Name"),
                ),
                (
                    "required_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="e.g., 25.00 for 25%",
                        max_digits=5,
                        verbose_name="Required Equity %",
                    ),
                ),
                (
                    "required_amount_nis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated: Total Project Cost × Required %",
                        max_digits=15,
                        verbose_name="Required Amount (NIS)",
                    ),
                ),
                (
                    "deadline_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Equity Deadline"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Equity Requirement",
                "verbose_name_plural": "Equity Requirements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(verbose_name="Snapshot Date")),
                (
                    "total_project_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Total Project Cost",
                    ),
                ),
                (
                    "required_equity_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Required Equity %"
                    ),
                ),
                (
                    "required_equity_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Required Equity Amount",
                    ),
                ),
                (
                    "validated_equity_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="All validated transactions by Team Manager",
                        max_digits=15,
                        verbose_name="Validated Equity Total",
                    ),
                ),
                (
                    "pending_validation_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Pending Validation Total",
                    ),
                ),
                (
                    "equity_gap",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Negative = surplus, Positive = deficit",
                        max_digits=15,
                        verbose_name="Equity Gap",
                    ),
                ),
                (
                    "equity_gap_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Gap as % of Required",
                    ),
                ),
                (
                    "generated_for_bank",
                    models.BooleanField(
                        default=False, verbose_name="Generated for Bank Submission"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bank Name"
                    ),
                ),
                (
                    "bank_submission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Submitted to Bank On"
                    ),
                ),
                (
                    "transactions_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="JSON snapshot of all transactions at this point in time",
                        verbose_name="Transactions Snapshot",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Equity Snapshot",
                "verbose_name_plural": "Equity Snapshots",
                "ordering": ["-snapshot_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquityTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("CASH_DEPOSIT", "Cash Deposit"),
                            ("LAND_PURCHASE", "Land Purchase"),
                            ("CONSULTANT_FEE", "Consultant Fee"),
                            ("DEV_LEVY", "Development Levy"),
                            ("PURCHASE_TAX", "Purchase Tax"),
                            ("PLANNING_FEE", "Planning Fee"),
                            ("ARCHITECT_FEE", "Architect Fee"),
                            ("ENGINEER_FEE", "Engineer Fee"),
                            ("LAWYER_FEE", "Lawyer Fee"),
                            ("SURVEY_FEE", "Survey Fee"),
                            ("OTHER_EXPENSE", "Other Expense"),
                        ],
                        max_length=50,
                        verbose_name="Transaction Type",
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="Transaction Date")),
                (
                    "paid_amount_nis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual amount paid by developer",
                        max_digits=15,
                        verbose_name="Amount Paid (NIS)",
                    ),
                ),
                (
                    "approved_amount_nis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount validated by Team Manager (may differ from paid amount)",
                        max_digits=15,
                        null=True,
                        verbose_name="Validated Amount (NIS)",
                    ),
                ),
                (
                    "source_calculator",
                    models.CharField(
                        blank=True,
                        help_text="e.g., LandCost_Lines, Suppliers_Lines",
                        max_length=100,
                        null=True,
                        verbose_name="Source Calculator",
                    ),
                ),
                (
                    "source_line_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Source Line ID"
                    ),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="equity/proofs/%Y/%m/",
                        verbose_name="Payment Proof",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Invoice Number"
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Receipt Number"
                    ),
                ),
                (
                    "check_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Check Number"
                    ),
                ),
                (
                    "bank_transfer_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Bank Transfer Reference",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Supplier/Payee Name"
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft (Not Submitted)"),
                            ("PENDING_VALIDATION", "Pending Team Manager Validation"),
                            ("VALIDATED", "Validated by Team Manager"),
                            ("REJECTED", "Rejected by Team Manager"),
                            ("APPROVED_BANK", "Approved by Bank"),
                        ],
                        default="DRAFT",
                        max_length=50,
                        verbose_name="Approval Status",
                    ),
                ),
                (
                    "submitted_for_validation_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Submitted for Validation Date",
                    ),
                ),
                (
                    "validated_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Validation Date"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, verbose_name="Rejection/Feedback from Team Manager"
                    ),
                ),
                (
                    "appraiser_notes",
                    models.TextField(blank=True, verbose_name="Appraiser Notes"),
                ),
                (
                    "manager_notes",
                    models.TextField(blank=True, verbose_name="Team Manager Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Equity Transaction",
                "verbose_name_plural": "Equity Transactions",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
