# Generated by Django 5.0.1 on 2025-11-19 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equity", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equityapprovalhistory",
            name="action_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equity_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equityrequirement",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equity_requirements",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="equityrequirement",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equity_requirements_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equitysnapshot",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equity_snapshots_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equitysnapshot",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equity_snapshots",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="equitytransaction",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equity_transactions",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="equitytransaction",
            name="submitted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equity_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitted By (Appraiser)",
            ),
        ),
        migrations.AddField(
            model_name="equitytransaction",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equity_validations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validated By (Team Manager)",
            ),
        ),
        migrations.AddField(
            model_name="equityapprovalhistory",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_history",
                to="equity.equitytransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="equitysnapshot",
            index=models.Index(
                fields=["project", "snapshot_date"],
                name="equity_equi_project_eaf49f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equitytransaction",
            index=models.Index(
                fields=["project", "approval_status"],
                name="equity_equi_project_3227d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equitytransaction",
            index=models.Index(
                fields=["transaction_date"], name="equity_equi_transac_a2d334_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equitytransaction",
            index=models.Index(
                fields=["submitted_by"], name="equity_equi_submitt_e25ce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equitytransaction",
            index=models.Index(
                fields=["validated_by"], name="equity_equi_validat_5265af_idx"
            ),
        ),
    ]
