# Generated by Django 5.0.1 on 2025-11-25 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_constructionprogress_constructionprogresssnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevLeviesLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("levy_type", models.CharField(max_length=200)),
                ("authority", models.CharField(blank=True, max_length=200)),
                ("is_equity_eligible", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Development Levy Line",
                "verbose_name_plural": "Development Levy Lines",
                "db_table": "devlevies_lines",
            },
        ),
        migrations.CreateModel(
            name="DevLeviesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Development Levy Summary",
                "verbose_name_plural": "Development Levy Summaries",
                "db_table": "devlevies_summary",
            },
        ),
        migrations.CreateModel(
            name="DirectBuildLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("work_type", models.CharField(blank=True, max_length=200)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Direct Build Line",
                "verbose_name_plural": "Direct Build Lines",
                "db_table": "directbuild_lines",
            },
        ),
        migrations.CreateModel(
            name="DirectBuildSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Direct Build Summary",
                "verbose_name_plural": "Direct Build Summaries",
                "db_table": "directbuild_summary",
            },
        ),
        migrations.CreateModel(
            name="ElectricityLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Electricity Line",
                "verbose_name_plural": "Electricity Lines",
                "db_table": "electricity_lines",
            },
        ),
        migrations.CreateModel(
            name="ElectricitySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Electricity Summary",
                "verbose_name_plural": "Electricity Summaries",
                "db_table": "electricity_summary",
            },
        ),
        migrations.CreateModel(
            name="LandCostLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("land_type", models.CharField(blank=True, max_length=200)),
                ("is_equity_eligible", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land Cost Line",
                "verbose_name_plural": "Land Cost Lines",
                "db_table": "landcost_lines",
            },
        ),
        migrations.CreateModel(
            name="LandCostSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land Cost Summary",
                "verbose_name_plural": "Land Cost Summaries",
                "db_table": "landcost_summary",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Line",
                "verbose_name_plural": "Maintenance Lines",
                "db_table": "maintenance_lines",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Summary",
                "verbose_name_plural": "Maintenance Summaries",
                "db_table": "maintenance_summary",
            },
        ),
        migrations.CreateModel(
            name="ManagementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Management Line",
                "verbose_name_plural": "Management Lines",
                "db_table": "management_lines",
            },
        ),
        migrations.CreateModel(
            name="ManagementSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Management Summary",
                "verbose_name_plural": "Management Summaries",
                "db_table": "management_summary",
            },
        ),
        migrations.CreateModel(
            name="OtherExpLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Other Expense Line",
                "verbose_name_plural": "Other Expense Lines",
                "db_table": "otherexp_lines",
            },
        ),
        migrations.CreateModel(
            name="OtherExpSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Other Expense Summary",
                "verbose_name_plural": "Other Expense Summaries",
                "db_table": "otherexp_summary",
            },
        ),
        migrations.CreateModel(
            name="OverheadLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overhead Line",
                "verbose_name_plural": "Overhead Lines",
                "db_table": "overhead_lines",
            },
        ),
        migrations.CreateModel(
            name="OverheadSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overhead Summary",
                "verbose_name_plural": "Overhead Summaries",
                "db_table": "overhead_summary",
            },
        ),
        migrations.CreateModel(
            name="PurchaseTaxALine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tax_type", models.CharField(blank=True, max_length=200)),
                ("is_equity_eligible", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Tax A Line",
                "verbose_name_plural": "Purchase Tax A Lines",
                "db_table": "purchasetaxa_lines",
            },
        ),
        migrations.CreateModel(
            name="PurchaseTaxASummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Tax A Summary",
                "verbose_name_plural": "Purchase Tax A Summaries",
                "db_table": "purchasetaxa_summary",
            },
        ),
        migrations.CreateModel(
            name="PurchaseTaxBLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tax_type", models.CharField(blank=True, max_length=200)),
                ("is_equity_eligible", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Tax B Line",
                "verbose_name_plural": "Purchase Tax B Lines",
                "db_table": "purchasetaxb_lines",
            },
        ),
        migrations.CreateModel(
            name="PurchaseTaxBSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Tax B Summary",
                "verbose_name_plural": "Purchase Tax B Summaries",
                "db_table": "purchasetaxb_summary",
            },
        ),
        migrations.CreateModel(
            name="RentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rent Line",
                "verbose_name_plural": "Rent Lines",
                "db_table": "rent_lines",
            },
        ),
        migrations.CreateModel(
            name="RentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rent Summary",
                "verbose_name_plural": "Rent Summaries",
                "db_table": "rent_summary",
            },
        ),
        migrations.CreateModel(
            name="SiteInsLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Insurance Line",
                "verbose_name_plural": "Site Insurance Lines",
                "db_table": "siteins_lines",
            },
        ),
        migrations.CreateModel(
            name="SiteInsSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Insurance Summary",
                "verbose_name_plural": "Site Insurance Summaries",
                "db_table": "siteins_summary",
            },
        ),
        migrations.CreateModel(
            name="SuppliersLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("supplier_name", models.CharField(max_length=200)),
                ("service_type", models.CharField(max_length=200)),
                ("is_equity_eligible", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suppliers Line",
                "verbose_name_plural": "Suppliers Lines",
                "db_table": "suppliers_lines",
            },
        ),
        migrations.CreateModel(
            name="SuppliersSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suppliers Summary",
                "verbose_name_plural": "Suppliers Summaries",
                "db_table": "suppliers_summary",
            },
        ),
        migrations.CreateModel(
            name="TenantsCompLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Compensation Line",
                "verbose_name_plural": "Tenant Compensation Lines",
                "db_table": "tenantscomp_lines",
            },
        ),
        migrations.CreateModel(
            name="TenantsCompSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Compensation Summary",
                "verbose_name_plural": "Tenant Compensation Summaries",
                "db_table": "tenantscomp_summary",
            },
        ),
        migrations.CreateModel(
            name="UnexpectedLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unexpected Cost Line",
                "verbose_name_plural": "Unexpected Cost Lines",
                "db_table": "unexpected_lines",
            },
        ),
        migrations.CreateModel(
            name="UnexpectedSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unexpected Cost Summary",
                "verbose_name_plural": "Unexpected Cost Summaries",
                "db_table": "unexpected_summary",
            },
        ),
        migrations.CreateModel(
            name="UpgradesLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upgrade Line",
                "verbose_name_plural": "Upgrade Lines",
                "db_table": "upgrades_lines",
            },
        ),
        migrations.CreateModel(
            name="UpgradesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upgrade Summary",
                "verbose_name_plural": "Upgrade Summaries",
                "db_table": "upgrades_summary",
            },
        ),
        migrations.CreateModel(
            name="VATCSLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(verbose_name="Line Number")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_5",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "month_6",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "VAT Line",
                "verbose_name_plural": "VAT Lines",
                "db_table": "vat_cs_lines",
            },
        ),
        migrations.CreateModel(
            name="VATCSSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lines",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_with_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=3, default=0.17, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_summary",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "VAT Summary",
                "verbose_name_plural": "VAT Summaries",
                "db_table": "vat_cs_summary",
            },
        ),
        migrations.CreateModel(
            name="MonthlyBudgetReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(help_text="The month of the report (1-12)"),
                ),
                ("year", models.IntegerField(help_text="The year of the report")),
                (
                    "total_budget_usage_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "prev_month_total_budget_usage_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "direct_building_usage_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "prev_month_direct_building_usage_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "construction_progress_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "prev_month_construction_progress_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "signed_contracts_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "prev_month_signed_contracts_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "qualified_sales_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "prev_month_qualified_sales_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "detailed_cost_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Stores the full cost breakdown table for the month.",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_reports",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("project", "year", "month")},
            },
        ),
    ]
