# Generated by Django 5.0.1 on 2025-11-26 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="actual_cash_out_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="actual_income_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="balance_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="bank_transactions_summary",
            field=models.JSONField(
                default=dict, help_text="Summary of bank transactions by category"
            ),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="cash_flow_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="checks_pending_approval",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="earned_cost_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="expected_income_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="financial_execution_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="financial_execution_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="physical_execution_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="physical_execution_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="physical_financial_gap_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="physical_financial_gap_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="report_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Sequential report number for this project"
            ),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="retention_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="monthlybudgetreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
